# Generated by Django 3.2.9 on 2021-11-21 13:09

import dynamic_filenames
from django.db import migrations

import account.utils.account


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=account.utils.account.stdimage_save_defaultimg(
                blank=True,
                default="default.jpg",
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}"
                ),
            ),
        ),
    ]
