FROM python:3.9.2-slim-buster

WORKDIR /app

RUN mkdir -p /pgdata

LABEL maintainer="PartyTeam"
LABEL description="GeoDjango..."

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get -y install netcat gcc postgresql \
    && apt-get clean

# Setup GDAL
RUN apt-get install -y binutils libproj-dev gdal-bin python-gdal python3-gdal

RUN pip install --upgrade pip

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY . /app