version: "3.9"

services:
  backend:
    build:
      context: ./PARTY/backend
      dockerfile: Dockerfile
      args:
        - DEV=true
    container_name: django_back
    command: >
      sh -c  "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./PARTY/backend:/app
    ports:
      - 0.0.0.0:8000:8000
    networks:
      - party_network
    depends_on:
      - db
      - cache

  db:
    image: postgres:15-alpine3.17
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 0.0.0.0:5433:5432
    networks:
      - party_network

  cache:
    image: redis:7.0-alpine3.17
    container_name: redis_cache
    restart: always
    ports:
      - 0.0.0.0:6379:6379
    networks:
      - party_network

  frontend:
    container_name: react_ui
    build:
      context: ./PARTY/ui
      dockerfile: Dockerfile
    command: npm start
    env_file:
      - .env
    restart: always
    volumes:
      - ./PARTY/ui:/app
    ports:
      - 0.0.0.0:3000:3000
    stdin_open: true
    depends_on:
      - backend
      - db
    networks:
      - party_network

networks:
  party_network:
    driver: bridge

volumes:
  pgdata:
