version: '3.3'

services:

  django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: party_app
    command: >
      sh -c "python manage.py wait_for_database &&
             python manage.py runserver_plus 0.0.0.0:8000"
    env_file:
      - .env
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - party_network
    depends_on:
      - db

  db:
    image: kartoza/postgis:14
    container_name: postgis_db
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - party_network

networks:
  party_network:
    driver: bridge

volumes:
  pgdata:
    # external:
      # name: pgdata