version: '3'

services:
  web:
    build: .
    command: python manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=party_db
      - POSTGRES_USER=lko
      - POSTGRES_PASSWORD=lko
    ports:
      - "5432:5432"