FROM python:3.9.2-slim-buster

# TODO: Try to switch to apine (RUN commands) - could be lighter
# FROM python:3.9.10-alpine3.15


WORKDIR /app

# RUN mkdir -p /pgdata

LABEL maintainer="PartyTeam"
LABEL description="GeoDjango..."

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get -y install netcat gcc postgresql \
    && apt-get clean

# RUN apk update \
# && apk upgrade \
# && apk add netcat-openbsd gcc postgresql


# Setup GDAL
RUN apt-get install -y binutils libproj-dev gdal-bin python-gdal python3-gdal

# RUN apk add binutils py3-gdal gdal proj

RUN pip install --upgrade pip

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY . /app