podman run -d \
    --name party_db \
    -e POSTGRES_PASSWORD=coderslab \
    -e POSTGRES_USER=postgres \
    -e POSTGRES_DB=dev2 \
    -p 5432:5432 \
    -v party_db:/var/lib/postgresql/data \
    docker.io/postgres

# FROM postgres:14-alpine