version: "3.9"

services:
  backend:
    build: .
#    command: python /app/manage.py runserver
    command: >
      sh -c  "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - party_network

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - party_network

volumes:
  postgres_data:

networks:
  party_network:
    driver: bridge
