FROM python:3.9.2-slim-buster

WORKDIR /django

LABEL maintainer="PartyTeam"
LABEL description="PartyWizard Backend"

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get -y install \
    && apt-get clean

RUN pip install --upgrade pip

# COPY ./requirements.txt /django/requirements.txt
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .