version: '3.9'

services:

  backend:
    build: .
    container_name: backend_django
    command: >
      sh -c  "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver"
    env_file:
      - .env
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - party_network
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine3.17
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - party_network

  frontend:
    container_name: react_front
    build:
      context: ./../front
      dockerfile: Dockerfile
    command: npm start
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - .env
    restart: always
    volumes:
      - ./../front:/app
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
      - db
    networks:
      - party_network

  redis:
    container_name: redis
    image: redis:7-alpine3.17
    ports:
      - 6379:6379
    networks:
      - party_network

  # to update content on nginx server it is necessary to npm run build react app at every change
  # nginx:
  #   container_name: nginx_server
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 80:8080
  #     - 433:433
  #   restart: always
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./nginx/gzip.conf:/etc/nginx/conf.d/gzip.conf:ro
  #     - ./PARTY/front/dist:/usr/share/nginx/html
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - party_network

networks:
  party_network:
    driver: bridge

volumes:
  pgdata:
