# Generated by Django 4.0.3 on 2022-04-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='user',
        ),
    ]
