# Generated by Django 4.0.3 on 2022-04-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_remove_announcement_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
