# Generated by Django 4.0.6 on 2022-08-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_image_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='category',
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='announcement.category'),
        ),
    ]
