# Generated by Django 4.0.3 on 2022-05-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_announcement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='announcement.servicecategory', verbose_name='announcement_categories'),
        ),
    ]
