# Generated by Django 4.0.7 on 2022-10-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_remove_announcement_category_announcement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ManyToManyField(related_name='announcements', to='announcement.image'),
        ),
    ]
