# Generated by Django 4.0.8 on 2022-10-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0008_announcement_updated_image_created_image_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='category',
            new_name='categories',
        ),
    ]
