# Generated by Django 4.0.7 on 2022-10-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0008_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='displayed',
            field=models.IntegerField(default=0),
        ),
    ]
