# Generated by Django 4.0.7 on 2022-10-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0009_announcement_updated_image_created_image_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='movie_url',
            field=models.ManyToManyField(related_name='announcement_movie', to='announcement.movie'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ManyToManyField(related_name='announcements_image', to='announcement.image'),
        ),
    ]
