# Generated by Django 4.0.8 on 2022-10-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0009_rename_category_announcement_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
