# Generated by Django 4.0.8 on 2022-10-12 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0011_rename_categories_announcement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='announcement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='announcement.announcement', verbose_name='announcement_%(class)ss'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='announcement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='announcement.announcement', verbose_name='announcement_%(class)ss'),
            preserve_default=False,
        ),
    ]
