# Generated by Django 4.0.3 on 2022-05-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0012_remove_announcement_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('muzyka', 'music'), ('cattering', 'cattering'), ('fotograf', 'photograph'), ('lokal', 'local'), ('animator', 'animator')], max_length=30),
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
