# Generated by Django 4.0.8 on 2022-10-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0013_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('MU', 'muzyka'), ('CA', 'cattering'), ('PH', 'fotograf'), ('LO', 'lokal'), ('AN', 'animator')], max_length=2),
        ),
    ]
