# Generated by Django 4.0.7 on 2022-10-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0009_announcement_displayed'),
        ('announcement', '0014_alter_category_options_alter_category_name'),
    ]

    operations = [
    ]
