# Generated by Django 4.0.7 on 2022-11-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0016_remove_announcement_displayed_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='views',
            old_name='uuid',
            new_name='uuid_or_email',
        ),
    ]
