# Generated by Django 4.0.7 on 2022-11-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0017_rename_uuid_views_uuid_or_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='uuid_or_email',
            field=models.UUIDField(db_index=True, editable=False, unique=True),
        ),
    ]
