# Generated by Django 4.0.3 on 2022-05-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0017_alter_announcement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='category',
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(choices=[('default', 'default'), ('wedding', 'Wedding...'), ('baptism', 'Baptism...'), ('integration', 'Integration...')], max_length=30),
        ),
    ]
