# Generated by Django 4.0.7 on 2022-11-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0018_alter_views_uuid_or_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='uuid_or_email',
            field=models.CharField(db_index=True, editable=False, max_length=240, unique=True),
        ),
    ]
