# Generated by Django 4.0.7 on 2022-11-05 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0019_alter_views_uuid_or_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='announcement.announcement'),
        ),
    ]
