# Generated by Django 4.0.7 on 2022-11-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0020_alter_views_announcement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='views',
            unique_together={('uuid_or_email', 'announcement')},
        ),
    ]
