# Generated by Django 4.0.7 on 2022-11-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0021_alter_views_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='uuid_or_email',
            field=models.CharField(db_index=True, editable=False, max_length=240),
        ),
    ]
