# Generated by Django 4.0.7 on 2022-11-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0022_alter_views_uuid_or_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('MU', 'Music'), ('CA', 'Cattering'), ('PH', 'Photographer'), ('LO', 'Place'), ('AN', 'Animator')], max_length=2),
        ),
    ]
