# Generated by Django 4.0.9 on 2023-02-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0024_alter_announcement_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('MU', 'Music'), ('CA', 'Catering'), ('PH', 'Photographer'), ('LO', 'Place'), ('AN', 'Animator')], max_length=2),
        ),
    ]
