# Generated by Django 3.2.9 on 2021-11-14 17:55

import account.utils.account
from django.db import migrations
import dynamic_filenames


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_alter_announcement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=account.utils.account.stdimage_save_defaultimg(blank=True, default='default.jpg', null=True, upload_to=dynamic_filenames.FilePattern(filename_pattern='{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}')),
        ),
    ]
