# Generated by Django 3.2.9 on 2021-11-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_announcement_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='AnnouncementImage',
        ),
    ]
