# Generated by Django 3.2.9 on 2021-11-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_rename_image_announcementimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('rodzinne', 'rodzinne'), ('biznesowe', 'biznesowe'), ('party', 'party')], default='rodzinne', max_length=100),
        ),
    ]
