# Generated by Django 3.2.9 on 2021-11-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0011_auto_20211115_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='category',
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='announcement.category', verbose_name='announcement_categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('lokal', 'lokal'), ('kapela', 'kapela'), ('fotograf', 'fotograf'), ('gastronomia', 'gastronomia')], default='lokal', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(choices=[('rodzinne', 'rodzinne'), ('biznesowe', 'biznesowe'), ('party', 'party')], default='party', max_length=100),
        ),
    ]
