# Generated by Django 3.2.9 on 2021-11-15 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0012_auto_20211115_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.announcementimage', verbose_name='announcement_images'),
        ),
    ]
