# Generated by Django 3.2.9 on 2021-11-18 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0016_auto_20211116_2205"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementimage",
            name="event_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="announcement.eventtype",
                verbose_name="event_type_image",
            ),
        ),
        migrations.AlterField(
            model_name="announcementimage",
            name="announcement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="announcement.announcement",
                verbose_name="announcement_image",
            ),
        ),
    ]
