# Generated by Django 3.2.9 on 2021-11-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0017_auto_20211118_1900"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnnouncementImage",
            new_name="Image",
        ),
    ]
