# Generated by Django 3.2.9 on 2021-11-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0018_rename_announcementimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="imagee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="announcement.image",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="event_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="announcement.eventtype",
                verbose_name="event_type_image",
            ),
        ),
    ]
