# Generated by Django 3.2.9 on 2021-11-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0019_auto_20211118_1928"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventtype",
            old_name="imagee",
            new_name="photo",
        ),
    ]
