# Generated by Django 3.2.9 on 2021-11-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0020_rename_imagee_eventtype_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ServiceCategory',
        ),
    ]
