# Generated by Django 3.2.9 on 2021-11-22 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0021_rename_category_servicecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='event_type',
            field=models.ManyToManyField(related_name='announcements', to='announcement.EventType'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='category',
            field=models.ManyToManyField(related_name='event_types', to='announcement.ServiceCategory'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='announcement.image', verbose_name='event_type_image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.eventtype', unique=True, verbose_name='event_type_image'),
        ),
    ]
