# Generated by Django 3.2.9 on 2021-11-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0022_auto_20211122_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='event_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.eventtype', verbose_name='event_type_image'),
        ),
    ]
