# Generated by Django 3.2.9 on 2021-11-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0023_alter_image_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
