# Generated by Django 3.2.9 on 2021-11-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0025_alter_announcement_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"ordering": ("-date",)},
        ),
    ]
