# Generated by Django 3.2.9 on 2021-11-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0026_alter_announcement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
