# Generated by Django 3.2.9 on 2021-12-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0027_alter_announcement_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
