# Generated by Django 3.2.9 on 2021-12-08 21:00

import dynamic_filenames
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0028_image_is_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}"
                ),
                verbose_name="images",
            ),
        ),
    ]
