# Generated by Django 3.2.9 on 2021-12-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0029_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_main',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
