# Generated by Django 3.2.9 on 2022-01-02 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0030_alter_image_is_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="announcement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="announcement.announcement",
                verbose_name="announcement_%(class)ss",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="event_type",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="announcement.eventtype",
                verbose_name="%(class)s",
            ),
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie",
                        to="announcement.announcement",
                        verbose_name="announcement_%(class)ss",
                    ),
                ),
                (
                    "event_type",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="announcement.eventtype",
                        verbose_name="%(class)s",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
