# Generated by Django 3.2.9 on 2022-01-03 18:00

import dynamic_filenames
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0031_auto_20220102_1455"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="movie",
            field=models.FileField(
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}"
                ),
            ),
        ),
    ]
