# Generated by Django 3.2.9 on 2022-01-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0031_announcement_city'),
        ('announcement', '0033_alter_movie_movie'),
    ]

    operations = [
    ]
