# Generated by Django 4.0.3 on 2022-05-03 19:19

import dynamic_filenames
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_remove_announcement_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='date',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=stdimage.models.StdImageField(blank=True, default='media/default.jpg', null=True, upload_to=dynamic_filenames.FilePattern(filename_pattern='{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}'), verbose_name='images'),
        ),
    ]
