# Generated by Django 4.0.3 on 2022-05-05 15:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_alter_announcement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
