# Generated by Django 4.0.3 on 2022-05-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0008_announcement_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='event',
            field=models.CharField(choices=[('default', 'default'), ('wedding', 'Wedding...'), ('baptism', 'Baptism...'), ('integration', 'Integration...')], default='default', max_length=30),
        ),
    ]
