# Generated by Django 4.0.3 on 2022-05-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0009_announcement_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('default', 'default'), ('wedding', 'Wedding...'), ('baptism', 'Baptism...'), ('integration', 'Integration...')], default='default', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='event',
        ),
        migrations.AddField(
            model_name='announcement',
            name='event_type',
            field=models.ManyToManyField(related_name='announcements', to='announcement.eventtype'),
        ),
    ]
