# Generated by Django 4.0.3 on 2022-05-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0014_announcement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='user',
        ),
        migrations.AddField(
            model_name='announcement',
            name='event_type',
            field=models.ManyToManyField(related_name='announcements', to='announcement.eventtype'),
        ),
    ]
