# Generated by Django 4.0.3 on 2022-05-17 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0021_announcement_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='announcement.category', verbose_name='announcement_categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('muzyka', 'music'), ('cattering', 'cattering'), ('fotograf', 'photograph'), ('lokal', 'local'), ('animator', 'animator')], max_length=25),
        ),
    ]
