# Generated by Django 4.0.3 on 2022-05-17 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0021_announcement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='announcement.category', verbose_name='announcement_categories'),
            preserve_default=False,
        ),
    ]
