# Generated by Django 4.0.3 on 2022-05-17 20:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0026_delete_eventtype_alter_announcement_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('muzyka', 'music'), ('cattering', 'cattering'), ('fotograf', 'photograph'), ('lokal', 'local'), ('animator', 'animator')], max_length=25)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='announcement.category', verbose_name='announcement_categories'),
        ),
    ]
