# Generated by Django 4.0.3 on 2022-05-17 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0027_category_alter_announcement_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='uuid',
        ),
    ]
