"""
Django admin customization.
"""
from django.contrib import admin
from django.utils.translation import gettext_lazy as _

from . import models


# @admin.register(models.Announcement)
class AnnouncementAdmin(admin.ModelAdmin):
    """Define the admin page for announcements."""

    ordering = ["id"]
    list_display = ("title", "created")
    prepopulated_fields = {
        # "slug": ("title",),
    }
    fieldsets = (
        (
            _("Announcement"),
            {
                "fields": (
                    "title",
                    "description",
                )
            },
        ),
        (
            _("Categories"),
            {
                "fields": (
                    "category",
                    # 'event',
                )
            },
        ),
        (
            _("Author"),
            {"fields": ("user",)},
        ),
        # (
        # _("Multimedia"),
        # {"fields": ("image",)},
        # ),
        (
            _("Autogenerated data"),
            {
                "fields": (
                    "slug",
                    "uuid",
                    "created",
                )
            },
        ),
    )
    readonly_fields = (
        "slug",
        "uuid",
        "created",
    )
    add_fieldsets = (
        None,
        {
            "classes": ("wide",),
            "fields": (
                "title",
                "description",
                "slug",
                "uuid",
                "user",
                "category",
            ),
        },
    )


class CategoryAdmin(admin.ModelAdmin):
    """Define the admin page for categories."""

    ordering = ["id"]
    list_display = ("name",)
    fieldsets = (
        (
            None,
            {
                "fields": (
                    "name",
                    "uuid",
                )
            },
        ),
    )
    readonly_fields = ("uuid",)
    add_fieldsets = (
        (
            None,
            {
                "classes": ("wide",),
                "fields": (
                    "name",
                    "uuid",
                ),
            },
        ),
    )


class ImageAdmin(admin.ModelAdmin):
    """Define the admin page for images."""

    ordering = ["id"]
    list_display = ("image",)
    fieldsets = (
        (
            None,
            {
                "fields": (
                    "image",
                    "is_main",
                    "announcement",
                ),
            },
        ),
    )
    readonly_fields = []
    add_fieldsets = (
        (
            None,
            {
                "classes": ("wide",),
                "fields": (
                    "image",
                    "is_main",
                    "announcement",
                ),
            },
        ),
    )


admin.site.register(models.Announcement, AnnouncementAdmin)
admin.site.register(models.Category, CategoryAdmin)
admin.site.register(models.Image, ImageAdmin)
