# Generated by Django 4.0.8 on 2023-01-28 11:06

from django.db import migrations, models
import dynamic_filenames


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_voicemessage_message_voice_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemessage',
            name='voice_message',
            field=models.FileField(upload_to=dynamic_filenames.FilePattern(filename_pattern='{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}.mp3')),
        ),
    ]
