# Generated by Django 4.0.10 on 2023-03-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_conversation_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='sender',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='recipient',
            new_name='seller',
        ),
    ]
