# FROM node:17.9-alpine3.15
FROM node:18-alpine3.15

WORKDIR /app

ENV PATH="./node_modules/.bin:$PATH"

LABEL maintainer="PartyTeam"
LABEL description="PartyWizard Frontend"

COPY package.json .

RUN npm install

COPY . .

RUN npm run build
# RUN npm run build && \
# adduser \
# --disabled-password \
# --no-create-home \
# react-user

# USER react-user