# FROM node:17.9-alpine3.15
FROM node:18-alpine3.15 as builder

WORKDIR /app

ENV PATH="./node_modules/.bin:$PATH"

LABEL maintainer="PartyTeam"
LABEL description="PartyWizard Frontend"

COPY package.json .

RUN npm install

COPY . .

RUN npm run build
# RUN npm run build && \
# adduser \
# --disabled-password \
# --no-create-home \
# react-user

# USER react-user


# FROM nginx:alpine

# COPY ./nginx.conf /etc/nginx/conf.d/default.conf:ro
# # COPY ./../../nginx/gzip.conf /etc/nginx/conf.d/gzip.conf:ro

# RUN rm -rf /usr/share/nginx/html/*

# COPY --from=builder /app/dist /usr/share/nginx/html

# EXPOSE 3000 80