# Generated by Django 4.0.8 on 2023-01-06 20:09

import back.utils.account
from django.db import migrations
import dynamic_filenames


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=back.utils.account.stdimage_save_defaultimg(blank=True, default='default.jpg', force_min_size=False, null=True, upload_to=dynamic_filenames.FilePattern(filename_pattern='{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}'), variations={'large': (600, 400), 'medium': (300, 200), 'small': (100, 100), 'thumbnail': (30, 30, True)}),
        ),
    ]
