FROM nginx:alpine
# FROM nginx:latest

# WORKDIR /usr/share/nginx/html

# RUN rm /etc/nginx/conf.d/default.conf
# RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# COPY nginx-setup.conf /etc/nginx/