# Generated by Django 3.2.9 on 2021-11-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("party_wizard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formmodel",
            old_name="test",
            new_name="form_party",
        ),
    ]
