# Generated by Django 3.2.9 on 2021-11-27 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("party_wizard", "0002_rename_test_formmodel_form_party"),
    ]

    operations = [
        migrations.AddField(
            model_name="formmodel",
            name="is_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="formmodel",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.user",
            ),
            preserve_default=False,
        ),
    ]
