# Generated by Django 3.2.9 on 2021-12-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_wizard', '0005_formmodel_form_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='form_party',
            field=models.JSONField(null=True),
        ),
    ]
