# Generated by Django 3.2.9 on 2022-01-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_wizard', '0006_alter_formmodel_form_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='form_party',
            field=models.JSONField(default={}, null=True),
        ),
    ]
